//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_delete {
            get {
                object obj = ResourceManager.GetObject("action_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document-new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_open {
            get {
                object obj = ResourceManager.GetObject("document-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Form1_button3_Click_Running {
            get {
                return ResourceManager.GetString("Form1_button3_Click_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test WPs.
        /// </summary>
        internal static string Form1_button3_Click_Test_WPs {
            get {
                return ResourceManager.GetString("Form1_button3_Click_Test_WPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  activated. Heal@.
        /// </summary>
        internal static string Form1_checkBox1_CheckedChanged__activated__Heal_ {
            get {
                return ResourceManager.GetString("Form1_checkBox1_CheckedChanged__activated__Heal_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  will auto follow: .
        /// </summary>
        internal static string Form1_checkBox1_CheckedChanged_1__will_auto_follow__ {
            get {
                return ResourceManager.GetString("Form1_checkBox1_CheckedChanged_1__will_auto_follow__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto heal for: .
        /// </summary>
        internal static string Form1_checkBox1_CheckedChanged_Auto_heal_for__ {
            get {
                return ResourceManager.GetString("Form1_checkBox1_CheckedChanged_Auto_heal_for__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXI not found.
        /// </summary>
        internal static string Form1_Form1_FFXI_not_found {
            get {
                return ResourceManager.GetString("Form1_Form1_FFXI_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed: .
        /// </summary>
        internal static string Form1_LevellingTimer_Tick_Killed__ {
            get {
                return ResourceManager.GetString("Form1_LevellingTimer_Tick_Killed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XI Mob List|*.ximbl.
        /// </summary>
        internal static string Form1_LoadMobListBtn_Click_XI_Mob_List___ximbl {
            get {
                return ResourceManager.GetString("Form1_LoadMobListBtn_Click_XI_Mob_List___ximbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Waypoints.
        /// </summary>
        internal static string Form1_LoadWayPointsBtn_Click_Loaded_Waypoints {
            get {
                return ResourceManager.GetString("Form1_LoadWayPointsBtn_Click_Loaded_Waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XI Way Points|*.xiwps.
        /// </summary>
        internal static string Form1_LoadWayPointsBtn_Click_XI_Way_Points___xiwps {
            get {
                return ResourceManager.GetString("Form1_LoadWayPointsBtn_Click_XI_Way_Points___xiwps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Skill List.
        /// </summary>
        internal static string Form1_LoadWSListBtn_Click_Loaded_Skill_List {
            get {
                return ResourceManager.GetString("Form1_LoadWSListBtn_Click_Loaded_Skill_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Mob List.
        /// </summary>
        internal static string Form1_SaveMobListBtn_Click_Saved_Mob_List {
            get {
                return ResourceManager.GetString("Form1_SaveMobListBtn_Click_Saved_Mob_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Waypoints.
        /// </summary>
        internal static string Form1_SaveWayPointsBtn_Click_Saved_Waypoints {
            get {
                return ResourceManager.GetString("Form1_SaveWayPointsBtn_Click_Saved_Waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Skill List.
        /// </summary>
        internal static string Form1_SaveWSListBtn_Click_Saved_Skill_List {
            get {
                return ResourceManager.GetString("Form1_SaveWSListBtn_Click_Saved_Skill_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XI Skill List|*.xiwsl.
        /// </summary>
        internal static string Form1_SaveWSListBtn_Click_XI_Skill_List___xiwsl {
            get {
                return ResourceManager.GetString("Form1_SaveWSListBtn_Click_XI_Skill_List___xiwsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string Form1_StartBotting_Click_START {
            get {
                return ResourceManager.GetString("Form1_StartBotting_Click_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string Form1_StartBotting_Click_STOP {
            get {
                return ResourceManager.GetString("Form1_StartBotting_Click_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way Points Cleared.
        /// </summary>
        internal static string Form1_WPDelete_Click_Way_Points_Cleared {
            get {
                return ResourceManager.GetString("Form1_WPDelete_Click_Way_Points_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Form1_WPRecord_Click_Record {
            get {
                return ResourceManager.GetString("Form1_WPRecord_Click_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string Form1_WPRecord_Click_Recording {
            get {
                return ResourceManager.GetString("Form1_WPRecord_Click_Recording", resourceCulture);
            }
        }
    }
}
